apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-web
  labels:
    app: coffee-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee-web
  template:
    metadata:
      labels:
        app: coffee-web
    spec:
      containers:
      - name: coffee-web
        image: pavithrar015/coffee-web:1.1 
        ports:
        - containerPort: 5000
