apiVersion: v1
kind: Service
metadata:
  name: coffee-web-service
spec:
  type: NodePort
  selector:
    app: coffee-web
  ports:
    - protocol: TCP
      port: 80          # External service port (ClusterIP)
      targetPort: 5000   # Container port
      nodePort: 31482    # Static NodePort (within 30000-32767 range)
